export const proofTemplate = {
  id: "CANCEL-ARRIVAL",
  name: "司机到达与取消费证明模板",
  version: "2026.07-demo",
  scenario: "取消费争议",
  factDefinitions: [
    { id: "F_GEOFENCE", label: "司机进入有效上车范围" },
    { id: "F_DWELL", label: "司机连续停留达到规定时长" },
    { id: "F_CONTACT", label: "取消前完成必要联系" },
    { id: "F_CANCEL_TIME", label: "取消发生在规则允许时间之后" },
    { id: "F_TRACE_CONTINUITY", label: "关键时间窗轨迹连续可用" },
  ],
  outcomes: [
    {
      id: "DRIVER_FULFILLED",
      label: "司机已完成到达与等待义务",
      conclusion:
        "现有证据支持司机已按规则到达并完成必要联系，不支持“司机未到达”的投诉主张。",
      action: "维持当前取消费处理；上车点体验异议转入体验问题队列。",
      requirements: [
        { factId: "F_GEOFENCE", status: "SUPPORTED", minQuality: "MEDIUM" },
        { factId: "F_DWELL", status: "SUPPORTED", minQuality: "MEDIUM" },
        { factId: "F_CONTACT", status: "SUPPORTED", minQuality: "MEDIUM" },
        { factId: "F_CANCEL_TIME", status: "SUPPORTED", minQuality: "MEDIUM" },
      ],
    },
    {
      id: "DRIVER_NOT_ARRIVED",
      label: "司机未完成到达义务",
      conclusion:
        "连续轨迹不支持司机进入有效上车范围，现有证据不足以认定司机已经到达。",
      action: "不支持向乘客收取本次取消费，并进入司机履约提醒流程。",
      requirements: [
        {
          factId: "F_TRACE_CONTINUITY",
          status: "SUPPORTED",
          minQuality: "HIGH",
        },
        {
          factId: "F_GEOFENCE",
          status: "CONTRADICTED",
          minQuality: "HIGH",
        },
      ],
    },
  ],
};

export const demoCases = [
  {
    id: "CASE-001",
    title: "证据充分 · 司机已履约",
    description: "轨迹、停留、联系与取消时间形成完整证据链。",
    scenario: "司机是否到达及取消费争议",
    claims: {
      driver: "我按导航到了上车点，等了六分多钟，也给乘客打过电话。",
      passenger: "我一直在商场门口，没有看到司机，我认为司机根本没到。",
    },
    facts: [
      {
        id: "F_GEOFENCE",
        status: "SUPPORTED",
        evidenceIds: ["E01", "E02"],
        note: "轨迹与到达事件相互印证。",
      },
      {
        id: "F_DWELL",
        status: "SUPPORTED",
        evidenceIds: ["E01"],
        note: "有效范围内连续停留 6 分 18 秒。",
      },
      {
        id: "F_CONTACT",
        status: "SUPPORTED",
        evidenceIds: ["E03"],
        note: "两次拨打，其中一次接通 21 秒。",
      },
      {
        id: "F_CANCEL_TIME",
        status: "SUPPORTED",
        evidenceIds: ["E04"],
        note: "取消发生在规则等待阈值之后。",
      },
      {
        id: "F_TRACE_CONTINUITY",
        status: "SUPPORTED",
        evidenceIds: ["E01"],
        note: "关键时间窗轨迹连续，定位质量正常。",
      },
    ],
    evidence: [
      {
        id: "E01",
        time: "14:31:42—14:38:00",
        title: "车辆连续 GPS 轨迹",
        summary: "14:31:42 进入有效范围，连续停留 6 分 18 秒。",
        source: "平台定位 SDK",
        quality: "HIGH",
      },
      {
        id: "E02",
        time: "14:31:50",
        title: "司机点击已到达",
        summary: "到达事件位置位于有效范围内。",
        source: "订单事件",
        quality: "MEDIUM",
      },
      {
        id: "E03",
        time: "14:33:10",
        title: "平台通话记录",
        summary: "两次拨打，一次接通 21 秒；不使用通话内容判责。",
        source: "平台通信服务",
        quality: "HIGH",
      },
      {
        id: "E04",
        time: "14:38:00",
        title: "订单取消事件",
        summary: "司机在到达事件后 6 分 10 秒取消订单。",
        source: "订单服务",
        quality: "HIGH",
      },
    ],
    expected: { gate: "AUTO_DECIDABLE", outcomeId: "DRIVER_FULFILLED" },
  },
  {
    id: "CASE-002",
    title: "证据不足 · 关键轨迹中断",
    description: "只有主动点击到达，缺少能够证明连续停留的轨迹。",
    scenario: "司机是否到达及取消费争议",
    claims: {
      driver: "我已经到达并等待了五分钟，平台应该可以看到。",
      passenger: "司机没有出现在我所在的位置，电话里也说不清楚。",
    },
    facts: [
      {
        id: "F_GEOFENCE",
        status: "UNKNOWN",
        evidenceIds: ["E11"],
        note: "主动点击事件不能单独证明车辆实际进入范围。",
      },
      {
        id: "F_DWELL",
        status: "UNKNOWN",
        evidenceIds: [],
        note: "14:34 后轨迹中断，无法计算连续停留。",
      },
      {
        id: "F_CONTACT",
        status: "SUPPORTED",
        evidenceIds: ["E12"],
        note: "存在一次未接通的拨打记录。",
      },
      {
        id: "F_CANCEL_TIME",
        status: "SUPPORTED",
        evidenceIds: ["E13"],
        note: "取消时间达到表面阈值，但前置到达事实未知。",
      },
      {
        id: "F_TRACE_CONTINUITY",
        status: "UNKNOWN",
        evidenceIds: [],
        note: "关键时间窗数据不完整。",
      },
    ],
    evidence: [
      {
        id: "E11",
        time: "14:32:03",
        title: "司机点击已到达",
        summary: "记录到主动点击事件，定位字段缺失。",
        source: "订单事件",
        quality: "LOW",
      },
      {
        id: "E12",
        time: "14:35:20",
        title: "平台通话记录",
        summary: "拨打一次，未接通。",
        source: "平台通信服务",
        quality: "HIGH",
      },
      {
        id: "E13",
        time: "14:37:15",
        title: "订单取消事件",
        summary: "点击到达后 5 分 12 秒取消。",
        source: "订单服务",
        quality: "HIGH",
      },
    ],
    expected: { gate: "INSUFFICIENT", outcomeId: null },
  },
  {
    id: "CASE-003",
    title: "证据冲突 · 事件与轨迹矛盾",
    description: "到达事件位于范围内，但连续轨迹显示车辆仍在外围道路。",
    scenario: "司机是否到达及取消费争议",
    claims: {
      driver: "系统已经提示我到达，我在附近等了乘客。",
      passenger: "地图上司机一直没有开进来，我没有找到车辆。",
    },
    facts: [
      {
        id: "F_GEOFENCE",
        status: "CONFLICTED",
        evidenceIds: ["E21", "E22"],
        note: "高质量轨迹与到达事件位置不一致。",
      },
      {
        id: "F_DWELL",
        status: "UNKNOWN",
        evidenceIds: ["E21"],
        note: "是否在业务有效范围内停留取决于冲突事实。",
      },
      {
        id: "F_CONTACT",
        status: "SUPPORTED",
        evidenceIds: ["E23"],
        note: "存在一次接通 13 秒的记录。",
      },
      {
        id: "F_CANCEL_TIME",
        status: "SUPPORTED",
        evidenceIds: ["E24"],
        note: "表面等待时长达到阈值。",
      },
      {
        id: "F_TRACE_CONTINUITY",
        status: "SUPPORTED",
        evidenceIds: ["E21"],
        note: "轨迹连续且定位质量高。",
      },
    ],
    evidence: [
      {
        id: "E21",
        time: "15:02:00—15:08:10",
        title: "车辆连续 GPS 轨迹",
        summary: "车辆持续位于上车点范围外 86—110 米。",
        source: "平台定位 SDK",
        quality: "HIGH",
      },
      {
        id: "E22",
        time: "15:02:05",
        title: "司机点击已到达",
        summary: "事件上报位置显示位于有效范围内。",
        source: "订单事件",
        quality: "MEDIUM",
      },
      {
        id: "E23",
        time: "15:04:13",
        title: "平台通话记录",
        summary: "接通 13 秒，不使用通话内容判责。",
        source: "平台通信服务",
        quality: "HIGH",
      },
      {
        id: "E24",
        time: "15:08:10",
        title: "订单取消事件",
        summary: "到达事件后 6 分 5 秒取消。",
        source: "订单服务",
        quality: "HIGH",
      },
    ],
    expected: { gate: "EVIDENCE_CONFLICT", outcomeId: null },
  },
  {
    id: "CASE-004",
    title: "证据充分 · 司机未到达",
    description: "关键时间窗轨迹连续，车辆始终未进入有效范围。",
    scenario: "司机是否到达及取消费争议",
    claims: {
      driver: "我就在乘客附近，只是商场定位不准。",
      passenger: "司机一直在外面的辅路，没有开到平台标出的上车点。",
    },
    facts: [
      {
        id: "F_GEOFENCE",
        status: "CONTRADICTED",
        evidenceIds: ["E31"],
        note: "车辆始终位于有效范围外 150 米以上。",
      },
      {
        id: "F_DWELL",
        status: "CONTRADICTED",
        evidenceIds: ["E31"],
        note: "有效范围内停留时长为 0。",
      },
      {
        id: "F_CONTACT",
        status: "SUPPORTED",
        evidenceIds: ["E32"],
        note: "联系行为成立，但不能替代到达义务。",
      },
      {
        id: "F_CANCEL_TIME",
        status: "SUPPORTED",
        evidenceIds: ["E33"],
        note: "等待时长表面达到阈值。",
      },
      {
        id: "F_TRACE_CONTINUITY",
        status: "SUPPORTED",
        evidenceIds: ["E31"],
        note: "关键时间窗轨迹连续，定位质量高。",
      },
    ],
    evidence: [
      {
        id: "E31",
        time: "18:20:00—18:27:30",
        title: "车辆连续 GPS 轨迹",
        summary: "车辆始终位于上车点有效范围外 150—240 米。",
        source: "平台定位 SDK",
        quality: "HIGH",
      },
      {
        id: "E32",
        time: "18:23:06",
        title: "平台通话记录",
        summary: "司机拨打一次并接通 18 秒。",
        source: "平台通信服务",
        quality: "HIGH",
      },
      {
        id: "E33",
        time: "18:27:30",
        title: "订单取消事件",
        summary: "司机发起取消。",
        source: "订单服务",
        quality: "HIGH",
      },
    ],
    expected: { gate: "AUTO_DECIDABLE", outcomeId: "DRIVER_NOT_ARRIVED" },
  },
];
